=== Malekhentati/TP1soa/src/Cinema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/Cinema" xmlns:tns="http://www.example.org/Cinema" elementFormDefault="qualified">

    <element name="Cinema" type="tns:cinema"></element>
    
    <complexType name="cinema">
    	<sequence>
    		<element name="Film" type="tns:film"></element>
    		<element name="Producteur" type="tns:producteur"></element>
    	</sequence>
    </complexType>
    <complexType name="film">
    	<sequence>
    		<element name="titre" type="string"></element>
    		<element name="année" type="string"></element>
    		<element name="réalisation" type="string"></element>
    	</sequence>
    	<attribute name="id" type="string"></attribute>
    	<attribute name="type" type="string"></attribute>
    </complexType>

    <complexType name="producteur">
    	<sequence>
    		<element name="nom" type="string"></element>
    		<element name="Film" type="string"></element>
    	</sequence>
    </complexType>
</schema>

=== Malekhentati/TP1soa/src/Cinema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Cinema xmlns:tns="http://www.example.org/Cinema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Cinema Cinema.xsd ">
  <tns:Film>
    <tns:titre>tns:titre</tns:titre>
    <tns:année>tns:année</tns:année>
    <tns:réalisation>tns:réalisation</tns:réalisation>
  </tns:Film>
  <tns:Producteur>
    <tns:nom>tns:nom</tns:nom>
    <tns:Film>tns:Film</tns:Film>
  </tns:Producteur>
</tns:Cinema>
